import os
import re
import tempfile
import pytest
from unittest.mock import Mock

from lib import subissues


def parse_txt_input(txt_content):
    """
    Parses the raw .txt file format generated by `_write_raw_jira_to_file`.
    Returns (description, comments_list)
    """
    # Split by the exact separator used in _write_raw_jira_to_file
    parts = txt_content.split("\n\n---\n\n# COMMENTS:\n\n")

    # If the file had no description, the txt file might start with the separator
    # but based on the code, if description exists, it writes it.
    description = parts[0] if parts[0] else None

    comments = []
    if len(parts) > 1:
        comments_section = parts[1]

        # Split by "by: " prefix (multiline)
        comment_blocks = re.split(r"^by: ", comments_section, flags=re.MULTILINE)
        for block in comment_blocks:
            if not block.strip():
                continue

            lines = block.split("\n", 1)
            if len(lines) >= 2:
                header = lines[0]
                body = lines[1]

                # Extract author and date
                author_date = header.split(" on ")
                if len(author_date) == 2:
                    author = author_date[0]
                    date = author_date[1]

                    mock_comment = Mock()
                    mock_comment.author = author
                    mock_comment.created = date
                    # Remove trailing newlines that were added by the exporter
                    # The exporter does: handle.write(comment.body + "\n\n")
                    # but wait, the original comment body might have trailing newlines.
                    # Using rstrip() is generally safe for comparison if we strip expected as well.
                    mock_comment.body = (
                        body[:-2] if body.endswith("\n\n") else body.rstrip("\n")
                    )
                    comments.append(mock_comment)

    return description, comments


def test_txt_to_md_mapping():
    """
    Tests that some of the input txt files in the "test_inputs" directory
    get correctly mapped to markdown files in the "test_expected_output" directory.
    """
    input_dir = "test_inputs"
    expected_dir = "test_expected_output"

    txt_files = [f for f in os.listdir(input_dir) if f.endswith(".txt")]
    assert len(txt_files) > 0, "No .txt files found in test_inputs directory"

    for filename in txt_files:
        issue_key = filename[:-4]
        input_path = os.path.join(input_dir, filename)
        expected_path = os.path.join(expected_dir, f"{issue_key}.md")

        assert os.path.exists(expected_path), f"Expected file {expected_path} missing"

        with open(input_path, "r", encoding="utf-8", newline="") as f:
            txt_content = f.read().replace("\r", "")

        with open(expected_path, "r", encoding="utf-8", newline="") as f:
            expected_md = f.read().replace("\r", "")

        # Extract summary from the first heading line of the expected markdown
        # (skip YAML frontmatter if present)
        lines = expected_md.split("\n")
        first_line = lines[0]
        prefix = f"# {issue_key}: "
        if first_line == "---":
            # Skip frontmatter block (ends at the next '---')
            end_frontmatter = next(
                (i for i, l in enumerate(lines[1:], 1) if l == "---"), None
            )
            if end_frontmatter is not None:
                first_line = lines[end_frontmatter + 1]
        assert first_line.startswith(prefix)
        summary_md = first_line[len(prefix) :]

        # Un-escape the markdown-escaped brackets to get the original JIRA summary
        original_summary = (
            summary_md.replace("\\[", "[")
            .replace("\\]", "]")
            .replace("\\(", "(")
            .replace("\\)", ")")
        )

        # We assume the summary in JIRA is the same as summary_md because
        # _convert_inline should ideally be somewhat idempotent for plain text summaries.
        # If it has Markdown special chars, it might get double-escaped, but these files are simple.

        description, comments = parse_txt_input(txt_content)

        # Create mocked JIRA objects
        mock_issue = Mock()
        mock_issue.key = issue_key
        mock_issue.fields.summary = original_summary
        mock_issue.fields.description = description

        mock_jira = Mock()
        mock_jira.comments.return_value = comments

        # Mock issue lookup to raise an exception so image downloads fall back to original string,
        # which matches the behavior in the sample outputs (which apparently failed to download images).
        mock_jira.issue.side_effect = Exception(
            "Mocked connection error for image download"
        )

        with tempfile.TemporaryDirectory() as tmpdir:
            result_md = subissues._to_string(mock_jira, mock_issue, tmpdir)

            # Use strip() to ignore trailing newline differences at EOF
            assert result_md.strip() == expected_md.strip(), (
                f"Mismatch in output for {filename}"
            )
